# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=1000, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name=b'child', to='website.PhysicalFolder')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('index', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name=b'child', to='website.VirtualFolder')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualFolderPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.VirtualFolder')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='virtualfolder',
            name='photos',
            field=models.ManyToManyField(related_name='virtual_folders', through='website.VirtualFolderPhotos', to='website.Photo'),
        ),
        migrations.AddField(
            model_name='photo',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.PhysicalFolder'),
        ),
        migrations.AlterUniqueTogether(
            name='virtualfolderphotos',
            unique_together=set([('folder', 'photo')]),
        ),
        migrations.AlterUniqueTogether(
            name='virtualfolder',
            unique_together=set([('parent', 'index'), ('parent', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='physicalfolder',
            unique_together=set([('parent', 'name')]),
        ),
    ]
