# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name=b'child', to='website.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('mtime', models.DateTimeField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('captured', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('raiting', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name=b'child', to='website.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VirtualFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('index', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name=b'child', to='website.VirtualFolder')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualFolderPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.VirtualFolder')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalFolderRoot',
            fields=[
                ('physicalfolder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.PhysicalFolder')),
                ('physicalpath', models.CharField(max_length=255, unique=True)),
            ],
            bases=('website.physicalfolder',),
        ),
        migrations.AddField(
            model_name='virtualfolder',
            name='photos',
            field=models.ManyToManyField(related_name='virtual_folders', through='website.VirtualFolderPhotos', to='website.Photo'),
        ),
        migrations.AddField(
            model_name='physicalfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name=b'child', to='website.PhysicalFolder'),
        ),
        migrations.AddField(
            model_name='photo',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.PhysicalFolder'),
        ),
        migrations.AddField(
            model_name='photo',
            name='people',
            field=models.ManyToManyField(related_name='photos', to='website.Person'),
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(related_name='photos', to='website.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='virtualfolderphotos',
            unique_together=set([('folder', 'photo')]),
        ),
        migrations.AlterUniqueTogether(
            name='virtualfolder',
            unique_together=set([('parent', 'index'), ('parent', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('parent', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='physicalfolder',
            unique_together=set([('parent', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set([('folder', 'filename')]),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('parent', 'name')]),
        ),
    ]
