# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalfolderroot',
            name='directurl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
